<?php ob_start() ?>
    <main class="allBandsPage">
        <div class="container">
            <section class="allBands">
                <h1>THE BAND</h1>
                
                <div class="allBandsArticle" >
                <?php foreach ($bands as $band): ?>
                    <article>
              
                        <a href="Band&name=<?= $band["slug"]."-".$band["id"] ?>" ><img class ="bandImg" src="./assets/images/bands/<?= $band["slug"]."/".$band["imageBand"] ?>"></a>
                        <h4><?= $band["name"] ?></h4>
                    
                    </article>
                <?php endforeach; ?>

                </div>
            
        </section>

        </div>
    </main>
    
<?php $content = ob_get_clean(); ?>