<?php ob_start() ?>
    <main class="allBandsPage">
        <div class="container">
            <section class="allBands">
                <h1>THE BAND</h1>
                
                <div class="allBandsArticle" >

                    <article>
              
                        <a href="Band"><img class ="bandImg" src="./assets/images/BabeRainbow_1024x1024.webp"></a>
                        <h4>Deedee & The Abracadabras</h4>
                    
                    </article>
                
                    <article>
                        
                        <a href=""><img class ="bandImg" src="./assets/images/BabeRainbow_1024x1024.webp"></a>
                        <h4>THE BAND</h4>
                        
                    </article>
                    <article>
                        
                        <a href=""><img class ="bandImg" src="./assets/images/BabeRainbow_1024x1024.webp"></a>
                        <h4>THE BAND</h4>
                    
                    </article>
                    <article>
                    
                        <a href=""><img class ="bandImg" src="./assets/images/BabeRainbow_1024x1024.webp"></a>
                        <h4>Deedee & The Abracadabras</h4>
                    
                    </article>
                
                    <article>
                    
                        <a href=""><img class ="bandImg" src="./assets/images/BabeRainbow_1024x1024.webp"></a>
                        <h4>THE BAND</h4>
                    
                    </article>
           

                </div>
            
        </section>

        </div>
    </main>
    
<?php $content = ob_get_clean(); ?>