
<?php ob_start() ?>  
   
   <main class="artistMain">
       <div class="container">
            
           <section>
                <h1 class="artistName"> Deedee & The Abracadabras</h1>
                
                
                <article class="artistArticle">
                    

                    <div class="artistsDescription">
                        
                        
                        <img class="artistImg"src=./assets/images/BabeRainbow_1024x1024.webp>
            
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo culpa vel neque, maxime ea laborum 
                            suscipit accusamus! In numquam necessitatibus vitae recusandae tenetur hic doloribus? Laudantium modi numquam natus sapiente.
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo culpa vel neque, maxime ea laborum 
                            suscipit accusamus! In numquam necessitatibus vitae recusandae tenetur hic doloribus? Laudantium modi numquam natus sapiente.
                        </p>
                        <ul class="artistLinks">
                            <li><a href="#">facebook</a></li>
                            <li><a href="#">facebook</a></li>
                            <li><a href="#">facebook</a></li>
                            <li><a href="#">facebook</a></li>
                        </ul>

                    </div>
                    
                    <div class="frames">
                        <iframe style="border: 0; width: 100%; height: 120px;" src="https://bandcamp.com/EmbeddedPlayer/album=2822830594/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/artwork=small/transparent=true/" seamless><a href="https://leceperecords.bandcamp.com/album/deedee-the-abracadabras">Deedee &amp; The Abracadabras by DEEDEE &amp; THE ABRACADABRAS</a></iframe>
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/wLdZAPk0uh0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>


                </article>  
           </section>

           <hr>
           
           <section >
            <h2>More Products from this Artist</h2>

            <div class ="allProducts">
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a0858355988_16.jpg"></a>
                    <div class="description">
                        <h1><a href="" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>
    
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a3872158123_16.jpg"></a>
                    <div class="description">
                        <h1><a href="" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>
    
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a0858355988_16.jpg"></a>
                    <div class="description">
                        <h1><a href="" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>
    
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a3872158123_16.jpg"></a>
                    <div class="description">
                        <h1><a href="" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a3872158123_16.jpg"></a>
                    <div class="description">
                        <h1><a href="./Deedee&TheAbracadabras.html" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>

            </div>
            
        </section>
           
        </div>
   </main>
   
<?php $content = ob_get_clean(); ?>  

