
<?php ob_start() ?>  
   
   <main class="artistMain">
       <div class="container">
            
           <section>
                <h1 class="artistName"> <?= $info["name"] ?></h1>
                
                
                <article class="artistArticle">
                    

                    <div class="artistsDescription">
                        
                        
                        <img class="artistImg"src=./assets/images/bands/<?= $info["slug"]."/".$info["imageBand"] ?>>
            
                        <p><?= $info["description"] ?></p>
                        <ul class="artistLinks">
                            <li><a class="facebook" href="<?= $info["linkFB"] ?>"><i class="fab fa-facebook-square"></i></a></li>
                            <li><a  href="<?= $info["linkInsta"] ?>"><img class="insta" src="./assets/images/instagram_ig_logo_icon_134013.svg" class="fab fa-youtube"></a></li>
                            <li><a class="youtube" href="<?= $info["linkYoutube"] ?>"><i class="fab fa-youtube"></i></a></li>
                        </ul>

                    </div>
                    
                    <div class="frames">
                        <iframe style="border: 0; width: 100%; height: 120px;" src="https://bandcamp.com/EmbeddedPlayer/album=2822830594/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/artwork=small/transparent=true/" seamless><a href="<?= $info["linkBandcamp"] ?>"></a></iframe>
                        <?= htmlspecialchars_decode($info["iframeYoutube"]) ?>
                    </div>


                </article>  
           </section>

           <hr>
           
           <section >
            <h2>More Products from this Artist</h2>

            <div class ="allProducts">
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a0858355988_16.jpg"></a>
                    <div class="description">
                        <h1><a href="" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>
    
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a3872158123_16.jpg"></a>
                    <div class="description">
                        <h1><a href="" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>
    
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a0858355988_16.jpg"></a>
                    <div class="description">
                        <h1><a href="" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>
    
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a3872158123_16.jpg"></a>
                    <div class="description">
                        <h1><a href="" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a3872158123_16.jpg"></a>
                    <div class="description">
                        <h1><a href="./Deedee&TheAbracadabras.html" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>

            </div>
            
        </section>
           
        </div>
   </main>
   
<?php $content = ob_get_clean(); ?>  

