
<?php ob_start() ?>  
   
   <main class="artistMain">
       <div class="container">
            
           <section>
                <h1 class="artistName"> <?= $info["name"] ?></h1>
                
                
                <article class="artistArticle">
                    

                    <div class="artistsDescription">
                        
                        
                        <img class="artistImg"src=./assets/images/bands/<?= $info["bandSlug"]."/".$info["imageBand"] ?>>
            
                        <p><?= $info["description"] ?></p>
                        <ul class="artistLinks">
                            <li><a class="facebook" href="<?= $info["linkFB"] ?>"><i class="fab fa-facebook-square"></i></a></li>
                            <li><a  href="<?= $info["linkInsta"] ?>"><img class="insta" src="./assets/images/instagram_ig_logo_icon_134013.svg" class="fab fa-youtube"></a></li>
                            <li><a class="youtube" href="<?= $info["linkYoutube"] ?>"><i class="fab fa-youtube"></i></a></li>
                        </ul>

                    </div>
                    
                    <div class="frames">
                        <?= htmlspecialchars_decode($info["iframeBandcamp"]) ?>
                        <?= htmlspecialchars_decode($info["iframeYoutube"]) ?>
                    </div>


                </article>  
           </section>

           <hr>
           
           <section >
            <h2>Products from <?= $info["name"] ?></h2>
         
            <div class ="allProducts">
          
            <?php foreach ($products as $product): ?>

                
                <article class = "productCard">
                    <a href="Product&name=<?= $id[0]."-".$product["id"]."-".$product["bandSlug"]."-".$product["slug"] ?>">
                        <img class=" img imgProduct" src="./assets/images/bands/<?= $product["bandSlug"]."/".$product["slug"]."/".$product["image"] ?>">
                        <img class="cache imgAlt imgProduct" src="./assets/images/bands/<?= $product["bandSlug"]."/".$product["slug"]."/".$product["imageAlt"] ?>">
                    </a>
                    <div class="description">
                        <h1><a href="#"  class="band"><?= $product["name"] ?></a></h1>
                        <h2><a href="Product&name=<?= $id[0]."-".$product["id"]."-".$product["bandSlug"]."-".$product["slug"] ?>" class="title"><?= $product["title"] ?></a></h2>
                        <p>Release Date: <?= $product["dateSortie"] ?></p>
                        <p>type: <?= $product["type"] ?></p>
                        <p>Price: <?= $product["price"] ?></p>
                       
                    </div>
                </article>
            <?php endforeach; ?>
         
            </div>
            
            
        </section>
           
        </div>
   </main>
   
<?php $content = ob_get_clean(); ?>  

