<?php ob_start() ?>
   <main>
        <div class="container">

            <section class ="allProducts">
            
            <?php foreach ($products as $product): ?>
                <article class = "productCard">
                    <a href="Product&name=<?= $product["id_band"]."-".$product["id"]."-".$product["bandSlug"]."-".$product["slug"] ?>" >
                        <img class="img imgProduct" src="./assets/images/bands/<?= $product["bandSlug"]."/".$product["slug"]."/".$product["image"] ?>">
                        <img class="imgAlt imgProduct cache" src="./assets/images/bands/<?= $product["bandSlug"]."/".$product["slug"]."/".$product["imageAlt"] ?>">
                    </a>
                    <div class="description">
                        <h1><a href="Band&name=<?= $product["id_band"]."-".$product["bandSlug"] ?>" class="band"><?= $product["name"] ?></a></h1>
                        <h2><a href="Product&name=<?= $product["id_band"]."-".$product["id"]."-".$product["bandSlug"]."-".$product["slug"] ?>" ><?= $product["title"] ?></a></h2>
                        <p>Release Date: <?= $product["dateSortie"] ?></p>
                        <p>type: <?= $product["type"] ?></p>
                        <p>Avail: <?= $product["dispo"] ?></p>
                        <p>Price: $<?= $product["price"] ?></p>
                    </div>
                </article>
                <?php endforeach; ?> 
            </section>
          
        </div>
    </main>

<?php $content = ob_get_clean(); ?>