<?php ob_start() ?>
   <main>
        <div class="container">

            <section class ="allProducts">
            

                <article class = "productCard">
                    <a href="../Controllers/Product.php" ><img class="imgProduct" src="././assets/images/a0858355988_16.jpg"></a>
                    <div class="description">
                        <h1><a href="Band" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="Product" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Avail: In stock</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a0858355988_16.jpg"></a>
                    <div class="description">
                        <h1><a href="" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Avail: In stock</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a0858355988_16.jpg"></a>
                    <div class="description">
                        <h1><a href="" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Avail: In stock</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a0858355988_16.jpg"></a>
                    <div class="description">
                        <h1><a href="" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Avail: In stock</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>

                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a3872158123_16.jpg"></a>
                    <div class="description">
                        <h1><a href="" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>

                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a0858355988_16.jpg"></a>
                    <div class="description">
                        <h1><a href="" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>

                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a3872158123_16.jpg"></a>
                    <div class="description">
                        <h1><a href="" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a3872158123_16.jpg"></a>
                    <div class="description">
                        <h1><a href="./Deedee&TheAbracadabras.html" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>
            </section>
          
        </div>
    </main>

<?php $content = ob_get_clean(); ?>