<!DOCTYPE html>
<html lang="en" id="page-top">
<head >
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" /> 
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">  
    <link href="./assets/css/nomalize.css" rel="stylesheet">
    <link href="./assets/css/style.css" rel="stylesheet">
    <title>Le cepe</title>
</head >
<body>
   <header >
       <div class="headerContainer">
           <div class="logo">
               <a  href="Home"><img class="logoimg" src="./assets/images/0018841217_100.png"></a>
           </div>
           <div>
               <nav id ="myBtn">
                   <a href="Artists">Artists</a>
                   <a href="Home">Products</a>
                   <a href="">About</a>
                   <a href="">FAQ</a>
               </nav>
           </div>
       </div>
   </header>

   <?= $content ?>


   <a class="scroll-to-top rounded js-scroll-trigger" href="#page-top">
        <i class="fas fa-angle-up"></i>
      </a>
     
  <script src="./assets/js/main.js"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="./vendor/jquery-easing/jquery.easing.js"></script>
  <script src="./assets/js/stylish-portfolio.js"></script>
</body>
</html>