<?php ob_start() ?>

   <main class="productPage">
    <div class="container">
        <section class="sectionProductPage">

            <article class="articleProductPage">
                <div class="divImgProduct">
                    <img  class="img ImgProduct" src="./assets/images/bands/<?= $product["bandSlug"]."/".$product["slug"]."/".$product["image"] ?>">
                    <img  class="imgAlt ImgProduct cache" src="./assets/images/bands/<?= $product["bandSlug"]."/".$product["slug"]."/".$product["imageAlt"] ?>">
                </div>
                <div class="refProduct">

                    <?php if ($product["name"] != "Le Cepe Records Merch"): ?>
                        <h1 class="band"><?= $product["name"] ?></h1>
                    <?php endif; ?>

                    <h2 class="title"><?= $product["title"] ?></h2>
                    
                    <?php if ($product["name"] != "Le Cepe Records Merch"): ?>
                        <p>Release Date: <?= $product["dateSortie"] ?></p>
                    <?php endif; ?>

                    <p>Type: <?= $product["type"] ?></p>
                    <p class="price"><?= $product["price"] ?>$</p>
                    <div class="divBuyButton"  >
                        <a class="buyButton" href="<?= $product["linkBandcamp"] ?>">Buy On BandCamp</a>
                    </div>

                    <div class="frames">
                        <?= htmlspecialchars_decode($product["iframeBandcamp"]) ?> 
                    </div>
                   
                </div>
                
            </article>
            
        </section>

        <hr>
           
        <section >
        <h2>More Products from this Artist</h2>

        
            <div class="otherProducts">

                <?php foreach ($moreProducts as $moreProduct): ?>
                    <article class = "productCard">
                        <a href="Product&le_cepe_records_merch=<?= $moreProduct["id_band"]."-".$moreProduct["id"]."-".$moreProduct["bandSlug"]."-".$moreProduct["slug"] ?>" >
                            <img class="img imgProduct" src="./assets/images/bands/<?= $moreProduct["bandSlug"]."/".$moreProduct["slug"]."/".$moreProduct["image"] ?>">
                            <img class="imgAlt imgProduct cache" src="./assets/images/bands/<?= $moreProduct["bandSlug"]."/".$moreProduct["slug"]."/".$moreProduct["imageAlt"] ?>">
                        </a>
                        <div class="description">
                            <h1 ><a class="band bandName" href="Band&le_cepe_records_artist=<?= $moreProduct["id_band"]."-".$moreProduct["bandSlug"] ?>" ><?= $moreProduct["name"] ?></a></h1>
                            <h2 ><a class ="albumTitle" href="Product&le_cepe_records_merch=<?= $moreProduct["id_band"]."-".$moreProduct["id"]."-".$moreProduct["bandSlug"]."-".$moreProduct["slug"] ?>" ><?= $moreProduct["title"] ?></a></h2>
                            
                            <p>Release Date: <?= $moreProduct["dateSortie"] ?></p>
                            <p>type: <?= $moreProduct["type"] ?></p>
                            <p>Avail: <?= $moreProduct["dispo"] ?></p>
                            <p>Price: $<?= $moreProduct["price"] ?></p>
                        </div>
                    </article>
                <?php endforeach; ?>
                
            </div>

        </section>
    </div>
    </main>
<?php $content = ob_get_clean(); ?>