<?php ob_start() ?>

   <main class="productPage">
    <div class="container">
        <section class="sectionProductPage">

            <article class="articleProductPage">
                <div class="divImgProduct">
                    <img  class="img ImgProduct" src="./assets/images/bands/<?= $product["bandSlug"]."/".$product["slug"]."/".$product["image"] ?>">
                    <img  class="imgAlt ImgProduct cache" src="./assets/images/bands/<?= $product["bandSlug"]."/".$product["slug"]."/".$product["imageAlt"] ?>">
                </div>
                <div class="refProduct">
                    <h1 class="band"><?= $product["name"] ?></h1>
                    <h2 class="title"><?= $product["title"] ?></h2>
                    <p>Release Date: <?= $product["dateSortie"] ?></p>
                    <p>Type: <?= $product["type"] ?></p>
                    <p class="price"><?= $product["price"] ?>$</p>
                    <div class="divBuyButton"  >
                        <a class="buyButton" href="<?= $product["linkBandcamp"] ?>">Buy On BandCamp</a>

                    </div>

                    <div class="frames">
                    <?= $product["iframeBandcamp"] ?> 
                    </div>
                   
                    
                </div>
                
            </article>
            
        </section>


   
        <hr>
           
           <section >
            <h2>More Products from this Artist</h2>

            <div class="allProducts">
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a0858355988_16.jpg"></a>
                    <div class="description">
                        <h1><a href="" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>
    
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a3872158123_16.jpg"></a>
                    <div class="description">
                        <h1><a href="" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>
    
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a0858355988_16.jpg"></a>
                    <div class="description">
                        <h1><a href="" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>
    
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a3872158123_16.jpg"></a>
                    <div class="description">
                        <h1><a href="" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>
                <article class = "productCard">
                    <a href="" ><img class="imgProduct" src="./assets/images/a3872158123_16.jpg"></a>
                    <div class="description">
                        <h1><a href="./Deedee&TheAbracadabras.html" class="band">Deedee & The Abracadabras</a></h1>
                        <h2><a href="" class="title">Deedee & The Abracadabras</a></h2>
                        <p>Release Date: 14/5/2021</p>
                        <p>type: Vinyl</p>
                        <p>Price: $40.00</p>
                    </div>
                </article>

            </div>
            
        </section>
    </div>
    </main>
<?php $content = ob_get_clean(); ?>