<?php ob_start() ?>
<h1 class="text-center">Gestion des Groupes</h1>

<a href="../Controllers/FormAddUpdateBands.php" class="btn btn-primary mb-3">Ajouter un groupe</a>
<table class="table text-center">
    <thead>
        <tr>
            <th>Nom</th>
            <th>Image Groupe</th>
            <th>Description</th>
            <th>Lien Facebook</th>
            <th>Lien Insta</th>
            <th>Lien Youtube</th>
            <th>Iframe BandCamp</th>
            <th>Iframe Youtube</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($infos as $info): ?>
       
            <tr>
                <td><?= $info["name"] ?></td>
                <td><img class="img-thumbnail" src=<?= "../../assets/images/bands/".$info["bandSlug"]."/".$info["imageBand"] ?> ></td>
                <td><?= substr($info["description"] , 0, 20)?></td>
                <td><?= $info["linkFB"] ?></td>
                <td><?= $info["linkInsta"] ?></td>
                <td><?= $info["linkYoutube"] ?></td>
                <td><?= substr($info["iframeBandcamp"] , 0, 10)?>...</td>
                <td><?= substr($info["iframeYoutube"] , 0, 10)?>...</td>
                
                <td><a class="btn btn-info" href="../Controllers/FormAddUpdateBands.php?id=<?= $info["id"]  ?>"><i class="fas fa-pen-fancy"></i></a></td>
                <td><a class="delete btn btn-danger " id="<?= $info["id"]  ?>" href="../Model/delete_band.php?id=<?= $info["id"]  ?>"><i class="fas fa-trash"></i></a></td>
            </tr>
        
        <?php endforeach; ?>
    </tbody>
</table>
<?php $content = ob_get_clean(); ?>  
