
<?php include 'headerAdmin.phtml'; ?> 

<div>
    <form action ="../Model/delete.php?id=<?= $_GET["id"] ?>" method="post">
        <label>Veuillez entrer votre password pour confirmer la supression des informations de <?= $info["Acess"] ?>  : </label>
        <input class="form-control" type="password" placeholder="Password current user" name="Password" required>
        <button class="btn btn-danger"type="submit">Suprimmer</button>
    </form>
</div>

<?php include 'footer.phtml'; ?> 