<?php ob_start() ?> 

<div class= container>
    <h1><?= $title ?></h1>
    <form action ="../Model/add_update_product.php" method="post" enctype="multipart/form-data">
        
        <div class="form-row col-6">


            <label>Titre: </label>
            <input  class="form-control" type="text" id="title" name="title" <?php if(isset($info)): ?> value="<?= $info["title"] ?>" <?php endif; ?>>
            
            <label>Groupe: </label>
            <select name="bands" id="bands" class="form-control" required>

                    <option value="">Selectionner un groupe</option>
                    <?php foreach ($listeBands as $band): ?>
                        <option value="<?= $band["id"] ?>" <?php if (isset($info) && $info["id_band"] == $band["id"]): ?> selected <?php endif; ?>><?= $band["name"] ?></option>
                    <?php endforeach; ?>

            </select>

            <label>Image: </label>
            <input class="form-control" type="file" id="image" name="image" <?php if(isset($info)): ?> value="<?= $info["image"] ?>" <?php endif; ?>>
            
            <label>Image Aternative: </label>
            <input class="form-control" type="file" id="imageAlt" name="imageAlt" <?php if(isset($info)): ?> value="<?= $info["imageAlt"] ?>" <?php endif; ?>>
            
            <label>Date: </label>
            <input class="form-control" type="text" id="dateSortie" name="dateSortie" <?php if(isset($info)): ?> value="<?= $info["dateSortie"] ?>" <?php endif; ?>>
    
            <label>Type: </label>
            <input class="form-control" type="text" id="type" name="type" <?php if(isset($info)): ?> value="<?= $info["type"] ?>" <?php endif; ?>> 
            
            <label>Prix: </label>
            <input class="form-control" type="text" id="price" name="price" <?php if(isset($info)): ?> value="<?= $info["price"] ?>" <?php endif; ?>>
        
            <label>Description: </label>
            <textarea class="form-control " type="text" id="description" name="description"><?php if(isset($info)): ?> <?= $info["description"] ?> <?php endif; ?> </textarea>
             
            <label>	Iframe Bandcamp: </label>
            <input class="form-control " type="text" id="iframeBandcamp" name="iframeBandcamp" <?php if(isset($info)): ?> value="<?= $info["iframeBandcamp"] ?>" <?php endif; ?>>

            <label>	Link Bandcamp: </label>
            <input class="form-control " type="text" id="linkBandcamp" name="linkBandcamp" <?php if(isset($info)): ?> value="<?= $info["linkBandcamp"] ?>" <?php endif; ?>>
            
           
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="dispo" id="New"   value="New"<?php if(isset($info) && $info["dispo"]=="New"): ?>checked<?php endif; ?>>
                <label class="form-check-label" for="New">New</label>
                </div>
                <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="dispo" id="Available"   value="Available"<?php if(isset($info) && $info["dispo"]=="Available"): ?>checked<?php endif; ?>>
                <label class="form-check-label" for="Available">Available</label>
                </div>
                <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="dispo" id="SoldOut"   value="Sold Out"<?php if(isset($info) && $info["dispo"]=="Sold Out"): ?>checked<?php endif; ?>>
                <label class="form-check-label" for="SoldOut">Sold Out</label>
            </div>
                
        </div>

        <?php if(isset($info)): ?> <input type="hidden"  name="id" value="<?= $info["id"] ?>" >  <?php endif; ?>
        <button class= "btn btn-success mt-5 mb-5" type= "submit">Valider</button>
        
    </form>
</div>
          
<?php $content = ob_get_clean(); ?>   