
   <!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width = device-width, initial-scale = 1.0">
        <meta http-equiv="X-UA-Compatible" content = "ie=edge">
        <title> <?= $title ?> </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    </head>
    
    <body>
        <header >

            <div class = "text-right">   
                <?php if($title === "Admin Gestion"): ?> 
                <a class="btn btn-danger" href="../Controllers/Deconnection.php">Déconnection</a>
                <?php endif; ?>
            </div>

        </header>

        <main>
            <div class="row">

                <div class="col-md-2 m-1">
                    <ul>
                        <li><a href="AdminGestion.php">Band</a></li>
                        <li><a href="AdminGestion.php">Product</a></li>
                        <li><a href="AdminGestion.php">Event</a></li>
                    </ul>
                </div>
        
                <div class="col-md-9 m-3">