
   <!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width = device-width, initial-scale = 1.0">
        <meta http-equiv="X-UA-Compatible" content = "ie=edge">
        <title> <?= $title ?> </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    </head>
    
    <body>
        <header >

            <div class = "text-right">   
                <?php if($title === "Gestion des Produits" || $title === "Gestion des Groupes" || $title === "Gestion Merchandising"): ?> 
                <a class="btn btn-danger" href="../Controllers/Deconnection.php">Déconnection</a>
                <?php endif; ?>
            </div>

        </header>

        <main>
            <div class="row">

                <div class="col-md-2 m-1">
                    <ul>
                        <li><a href="BandGestion.php">Bands</a></li>
                        <li><a href="ProductGestion.php">Bands Products</a></li>
                        <li><a href="MerchGestion.php">Le Cèpe Records Merch</a></li>
                    </ul>
                </div>
        
                <div class="col-md-9 m-3">

                <?= $content ?>

                </div>
            </div>
        </main>
        <footer></footer>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src ="../../assets/js/Backoffice/main.js"></script>  
    </body>
</html> 