<?php ob_start() ?>


<?php if($chooseProductsToDisplay == "Products"): ?>
    <h1 class="text-center">Gestion des Produits</h1>
<?php else: ?>
    <h1 class="text-center">Gestion du Merchandising</h1>
<?php endif; ?>

<a href="../Controllers/FormAddUpdateProducts.php" class="btn btn-primary mb-3">Ajouter un produit</a>
<table class="table text-center">
    <thead>
        <tr>
        
            <th>Titre</th>

            <?php if($chooseProductsToDisplay == "Products"): ?>
                <th>Groupe</th>
            <?php endif; ?>

            <th>Image</th>
            <th>Image Alt</th>
            
            <th>Type</th>
            <th>Prix</th>
            <th>Description</th>
            <th>Dispo</th>
            <th>Link BandCamp</th>

            <?php if($chooseProductsToDisplay == "Products"): ?>
                <th>Date</th>
                <th>Iframe BandCamp</th>
            <?php endif; ?>

            <th>Modifier</th>
            <th>Supprimer</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($infos as $info): ?>
            <tr>
                <td><?= $info["title"] ?></td>

                <?php if($chooseProductsToDisplay == "Products"): ?>
                    <td><?= $info["name"] ?></td>
                <?php endif; ?>

                <td><img class="img-thumbnail" src=<?= "../../assets/images/bands/".$info["bandSlug"]."/".$info["slug"]."/".$info["image"] ?> ></td>
                <td><img class="img-thumbnail" src=<?= "../../assets/images/bands/".$info["bandSlug"]."/".$info["slug"]."/".$info["imageAlt"] ?> ></td>
                
                <td><?= $info["type"] ?></td>
                <td><?= $info["price"] ?></td>
                <td><?= substr($info["description"] , 0,10)?>...</td>
                <td><?= $info["dispo"] ?></td>
                <td>...<?= substr($info["linkBandcamp"] , 35, 30)?>...</td>
                
                <?php if($chooseProductsToDisplay == "Products"): ?>
                    <td><?= $info["dateSortie"] ?></td>
                    <td><?= substr($info["iframeBandcamp"] , 0, 10)?>...</td>
                <?php endif; ?>
                
                
                <td><a class="btn btn-info" href="../Controllers/FormAddUpdateProducts.php?id=<?= $info["id"]  ?>"><i class="fas fa-pen-fancy"></i></a></td>
                <td><a class="delete btn btn-danger " id="<?= $info["id"]  ?>" href="../Model/delete_product.php?id=<?= $info["id"]  ?>"><i class="fas fa-trash"></i></a></td>
            </tr>

        <?php endforeach; ?>
    </tbody>
</table>


    
<?php $content = ob_get_clean(); ?>