<?php ob_start() ?>

<h1 class="text-center">Gestion des Produits</h1>

<a href="../Controllers/FormAddUpdateProducts.php" class="btn btn-primary mb-3">Ajouter un produit</a>
<table class="table">
    <thead>
        <tr>
            <th>Titre</th>
            <th>Band</th>
            <th>Date</th>
            <th>Type</th>
            <th>Prix</th>
            <th>Info</th>
            <th>Lien BandCamp</th>
            <th>Dispo</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($infos as $info): ?>
            <tr>
                <td><?= $info["title"] ?></td>
                <td><?= $info["id_band"] ?></td>
                <td><?= $info["dateSortie"] ?></td>
                <td><?= $info["type"] ?></td>
                <td><?= $info["price"] ?></td>
                <td><?= $info["description"] ?></td>
                <td><?= $info["linkBandcamp"] ?></td>
                <td><?= $info["dispo"] ?></td>
                
                <td><a class="btn btn-info" href="../Controllers/FormAddUpdateProducts.php?id=<?= $info["id"]  ?>"><i class="fas fa-pen-fancy"></i></a></td>
                <td><a class="delete btn btn-danger " id="<?= $info["id"]  ?>" href="../Model/delete_product.php?id=<?= $info["id"]  ?>"><i class="fas fa-trash"></i></a></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
    
<?php $content = ob_get_clean(); ?>